# Generated by Django 5.1.1 on 2024-09-12 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_discounted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('G', 'Ghee'), ('CB', 'ChickenBatter'), ('CW', 'ChickenWings'), ('C', 'Chicken'), ('M', 'MilkShake'), ('F', 'Fish'), ('B', 'Beef'), ('E', 'Eggs')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('Kigali City - Gasabo', 'Gasabo'), ('Kigali City - Kicukiro', 'Kicukiro'), ('Kigali City - Nyarugenge', 'Nyarugenge'), ('Northern Province - Burera', 'Burera'), ('Northern Province - Gakenke', 'Gakenke'), ('Northern Province - Gicumbi', 'Gicumbi'), ('Northern Province - Musanze', 'Musanze'), ('Northern Province - Rulindo', 'Rulindo'), ('Southern Province - Gisagara', 'Gisagara'), ('Southern Province - Huye', 'Huye'), ('Southern Province - Kamonyi', 'Kamonyi'), ('Southern Province - Muhanga', 'Muhanga'), ('Southern Province - Nyamagabe', 'Nyamagabe'), ('Southern Province - Nyanza', 'Nyanza'), ('Southern Province - Nyaruguru', 'Nyaruguru'), ('Southern Province - Ruhango', 'Ruhango'), ('Eastern Province - Bugesera', 'Bugesera'), ('Eastern Province - Gatsibo', 'Gatsibo'), ('Eastern Province - Kayonza', 'Kayonza'), ('Eastern Province - Kirehe', 'Kirehe'), ('Eastern Province - Ngoma', 'Ngoma'), ('Eastern Province - Nyagatare', 'Nyagatare'), ('Eastern Province - Rwamagana', 'Rwamagana'), ('Western Province - Karongi', 'Karongi'), ('Western Province - Ngororero', 'Ngororero'), ('Western Province - Nyabihu', 'Nyabihu'), ('Western Province - Nyamasheke', 'Nyamasheke'), ('Western Province - Rubavu', 'Rubavu'), ('Western Province - Rusizi', 'Rusizi'), ('Western Province - Rutsiro', 'Rutsiro')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
